# Generated by Django 4.2.7 on 2024-03-07 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.SmallIntegerField()),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
